# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2026-01-18T21:22:03+00:00

from __future__ import annotations

from pydantic import BaseModel


class CharacterWinRate(BaseModel):
    battle_count: int
    character_id: int
    win_count: int
    character_name: str
    character_alpha: str
    character_tool_name: str
    character_sort: int


class WinRateResponse(BaseModel):
    character_win_rates: list[CharacterWinRate]
